name: icl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - torch==2.1.0
  - transformers==4.32.0
  - datasets==2.9.0
  - evaluate==0.4.0
  - rouge_score==0.1.0
  - scipy==1.10.0
  - numpy==1.24.0
  - tqdm==4.65.0
  - accelerate==0.22.0
  - bitsandbytes==0.39.0
  - pip:
      - huggingface-hub==0.27.1
      - safetensors==0.5.1
