name: icl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.0
  - scipy=1.10.0
  - tqdm=4.65.0
  - pip:
    - torch==2.1.0
    - rouge_score==0.1.0
    - transformers==4.32.0
    - datasets==2.9.0
    - evaluate==0.4.0
   
